FROM golang:1.18

WORKDIR /build
ADD ./ /build

RUN apt install bash

RUN go install github.com/ferranbt/fastssz/sszgen@latest
RUN go install github.com/mgechev/revive@latest
RUN go install honnef.co/go/tools/cmd/staticcheck@master

RUN make build

ENTRYPOINT ["bash"]
# CMD ["-h"]
